# The purpose of this docker-compose file is to set up a local development / test environment
version: '3.7'
services:
  mysql:
    image: mysql:5.7.15
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=root
    - MYSQL_DATABASE=smokefree

  smokefree-initiative-service:
#    image: localmotion/smokefree-initiative-service:local
    image: localmotion/smokefree-initiative-service:latest
    restart: on-failure
    depends_on:
    - mysql
    ports:
    - "8086:8086"
    environment:
      - MICRONAUT_SERVER_PORT=8086
      - MICRONAUT_ENVIRONMENTS=local
      - MYSQL_JDBC_URL=jdbc:mysql://mysql:3306/smokefree?verifyServerCertificate=false&useSSL=true
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
      - AWS_COGNITO_USERPOOLID=eu-west-1_WsTxYUHyC

  onboarding-web:
    # image: localmotion/onboarding-web:latest
    image: onbweb:2
    restart: on-failure
    depends_on:
    - smokefree-initiative-service
    ports:
    - "3000:80"
    environment:
    - ONBOARDING_API=http://smokefree-initiative-service:8086/api/graphql
    - AUTHSWITCH=#           # Leave blank to activate the http password and set to AUTHSWITCH=# to disable the HTTP password
    - HTPASSWD=admin:$$apr1$$Jv46odcT$$pQwDyrm.Y2NMQ0E045ip01     # (user=admin, pw=admin) Note that for docker compose escaping $ signs have been replaced by $$
