version: '3.7'
services:
  mysql:
    image: mysql:5.7.15
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=smokefree

  smokefree-initiative-service:
#    image: localmotion/smokefree-initiative-service:local
    image: localmotion/smokefree-initiative-service
    restart: on-failure
    depends_on:
    - axonserver
    ports:
    - "8086:8086"
    environment:
      - MICRONAUT_SERVER_PORT=8086

  onboarding-web:
#    image: localmotion/onboarding-web:local
    image: localmotion/onboarding-web
    restart: on-failure
    depends_on:
    - smokefree-initiative-service
    ports:
    - "3000:80"
    environment:
    - ONBOARDING_API=http://smokefree-initiative-service:8086/graphql
