version: '3.7'
services:
  axonserver:
    image: axoniq/axonserver
    restart: on-failure
    # Persisting axon's data is desirable
#    volumes:
#    - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "8024:8024"
      - "8124:8124"

  smokefree-initiative-service:
    build: ../../smokefree-initiative-service/.
     image: localmotion/smokefree-initiative-service:local
#    image: localmotion/smokefree-initiative-service
    restart: on-failure
    depends_on:
    - axonserver
    ports:
    - "18086:18086"
    environment:
      - AXON_SERVERS=axonserver
      - MICRONAUT_SERVER_PORT=18086
